apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-tracking-server
  labels:
      app: mlflow-tracking-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-tracking-server-pods
  template:
    metadata:
      labels:
        app: mlflow-tracking-server-pods
    spec:
      containers:
        - name: mlflow-tracking-server-pod
          image: davidcjw/example-mlflow:1.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          imagePullPolicy: Always
          env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mlflow-postgresql-credentials
                key: postgresql-password
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mlflow-configmap
                key: DB_USERNAME
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: mlflow-configmap
                key: DB_HOST
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: mlflow-configmap
                key: DB_NAME
          - name: DEFAULT_ARTIFACT_ROOT
            valueFrom:
              configMapKeyRef:
                name: mlflow-configmap
                key: DEFAULT_ARTIFACT_ROOT
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mlflow-tracking-server
  name: mlflow-tracking-server
spec:
  type: NodePort
  selector:
    app: mlflow-tracking-server-pods
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30100